{% set name = "disdrodb" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/disdrodb-{{ version }}.tar.gz
  sha256: 6381349dd2e24bbe355a7d8d771b6b85058f87b0a02e05ccd3b2ef1b18a18f2e

build:
  entry_points:
    - disdrodb_initialize_station = disdrodb.cli.disdrodb_initialize_station:disdrodb_initialize_station
    - disdrodb_data_archive_directory = disdrodb.cli.disdrodb_data_archive_directory:disdrodb_data_archive_directory
    - disdrodb_metadata_archive_directory = disdrodb.cli.disdrodb_metadata_archive_directory:disdrodb_metadata_archive_directory
    - disdrodb_download_metadata_archive = disdrodb.cli.disdrodb_download_metadata_archive:disdrodb_download_metadata_archive
    - disdrodb_check_metadata_archive = disdrodb.cli.disdrodb_check_metadata_archive:disdrodb_check_metadata_archive
    - disdrodb_open_metadata_archive = disdrodb.cli.disdrodb_open_metadata_archive:disdrodb_open_metadata_archive
    - disdrodb_open_data_archive = disdrodb.cli.disdrodb_open_data_archive:disdrodb_open_data_archive
    - disdrodb_open_logs_directory = disdrodb.cli.disdrodb_open_logs_directory:disdrodb_open_logs_directory
    - disdrodb_open_metadata_directory = disdrodb.cli.disdrodb_open_metadata_directory:disdrodb_open_metadata_directory
    - disdrodb_open_product_directory = disdrodb.cli.disdrodb_open_product_directory:disdrodb_open_product_directory
    - disdrodb_open_readers_directory = disdrodb.cli.disdrodb_open_readers_directory:disdrodb_open_readers_directory
    - disdrodb_download_archive = disdrodb.cli.disdrodb_download_archive:disdrodb_download_archive
    - disdrodb_download_station = disdrodb.cli.disdrodb_download_station:disdrodb_download_station
    - disdrodb_upload_archive = disdrodb.cli.disdrodb_upload_archive:disdrodb_upload_archive
    - disdrodb_upload_station = disdrodb.cli.disdrodb_upload_station:disdrodb_upload_station
    - disdrodb_run_l0a_station = disdrodb.cli.disdrodb_run_l0a_station:disdrodb_run_l0a_station
    - disdrodb_run_l0a = disdrodb.cli.disdrodb_run_l0a:disdrodb_run_l0a
    - disdrodb_run_l0b_station = disdrodb.cli.disdrodb_run_l0b_station:disdrodb_run_l0b_station
    - disdrodb_run_l0b = disdrodb.cli.disdrodb_run_l0b:disdrodb_run_l0b
    - disdrodb_run_l0c_station = disdrodb.cli.disdrodb_run_l0c_station:disdrodb_run_l0c_station
    - disdrodb_run_l0c = disdrodb.cli.disdrodb_run_l0c:disdrodb_run_l0c
    - disdrodb_run_l0_station = disdrodb.cli.disdrodb_run_l0_station:disdrodb_run_l0_station
    - disdrodb_run_l0 = disdrodb.cli.disdrodb_run_l0:disdrodb_run_l0
    - disdrodb_run_l1_station = disdrodb.cli.disdrodb_run_l1_station:disdrodb_run_l1_station
    - disdrodb_run_l1 = disdrodb.cli.disdrodb_run_l1_station:disdrodb_run_l1_station
    - disdrodb_run_l2e_station = disdrodb.cli.disdrodb_run_l2e_station:disdrodb_run_l2e_station
    - disdrodb_run_l2e = disdrodb.cli.disdrodb_run_l2e_station:disdrodb_run_l2e_station
    - disdrodb_run_l2m_station = disdrodb.cli.disdrodb_run_l2m_station:disdrodb_run_l2m_station
    - disdrodb_run_l2m = disdrodb.cli.disdrodb_run_l2m_station:disdrodb_run_l2m_station
    - disdrodb_create_summary_station = disdrodb.cli.disdrodb_create_summary_station:disdrodb_create_summary_station
    - disdrodb_create_summary = disdrodb.cli.disdrodb_create_summary:disdrodb_create_summary
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - click
    - tqdm
    - pooch
    - donfig
    - requests
    - pyyaml
    - trollsift
    - netcdf4
    - pyarrow
    - pandas
    - dask
    - distributed
    - bokeh >=3.1.0
    - xarray
    - scipy
    - setuptools
    - matplotlib-base
    - tectonic
    - scikit-learn

test:
  imports:
    - disdrodb
  commands:
    - pip check
    - disdrodb_initialize_station --help
    - disdrodb_data_archive_directory --help
    - disdrodb_metadata_archive_directory --help
    - disdrodb_download_metadata_archive --help
    - disdrodb_check_metadata_archive --help
    - disdrodb_open_metadata_archive --help
    - disdrodb_open_data_archive --help
    - disdrodb_open_logs_directory --help
    - disdrodb_open_metadata_directory --help
    - disdrodb_open_product_directory --help
    - disdrodb_open_readers_directory --help
    - disdrodb_download_archive --help
    - disdrodb_download_station --help
    - disdrodb_upload_archive --help
    - disdrodb_upload_station --help
    - disdrodb_run_l0a_station --help
    - disdrodb_run_l0a --help
    - disdrodb_run_l0b_station --help
    - disdrodb_run_l0b --help
    - disdrodb_run_l0c_station --help
    - disdrodb_run_l0c --help
    - disdrodb_run_l0_station --help
    - disdrodb_run_l0 --help
    - disdrodb_run_l1_station --help
    - disdrodb_run_l1 --help
    - disdrodb_run_l2e_station --help
    - disdrodb_run_l2e --help
    - disdrodb_run_l2m_station --help
    - disdrodb_run_l2m --help
    - disdrodb_create_summary_station --help
    - disdrodb_create_summary --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ltelab/disdrodb
  summary: disdrodb provides tools to download, standardize, share and analyze global disdrometer data.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ghiggi
