{% set name = "disdrodb" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/disdrodb-{{ version }}.tar.gz
  sha256: 5320ce254c7b91096fe9bf75cbf3aa64dfb30eeb11463c327d677294d88f8d82

build:
  entry_points:
    - disdrodb_initialize_station = disdrodb.api.scripts.disdrodb_initialize_station:disdrodb_initialize_station
    - disdrodb_check_metadata_archive = disdrodb.metadata.scripts.disdrodb_check_metadata_archive:disdrodb_check_metadata_archive
    - disdrodb_download_archive = disdrodb.data_transfer.scripts.disdrodb_download_archive:disdrodb_download_archive
    - disdrodb_download_station = disdrodb.data_transfer.scripts.disdrodb_download_station:disdrodb_download_station
    - disdrodb_upload_archive = disdrodb.data_transfer.scripts.disdrodb_upload_archive:disdrodb_upload_archive
    - disdrodb_upload_station = disdrodb.data_transfer.scripts.disdrodb_upload_station:disdrodb_upload_station
    - disdrodb_run_l0a_station = disdrodb.l0.scripts.disdrodb_run_l0a_station:disdrodb_run_l0a_station
    - disdrodb_run_l0a = disdrodb.l0.scripts.disdrodb_run_l0a:disdrodb_run_l0a
    - disdrodb_run_l0b_station = disdrodb.l0.scripts.disdrodb_run_l0b_station:disdrodb_run_l0b_station
    - disdrodb_run_l0_station = disdrodb.l0.scripts.disdrodb_run_l0_station:disdrodb_run_l0_station
    - disdrodb_run_l0b_concat_station = disdrodb.l0.scripts.disdrodb_run_l0b_concat_station:disdrodb_run_l0b_concat_station
    - disdrodb_run_l0b_concat = disdrodb.l0.scripts.disdrodb_run_l0b_concat:disdrodb_run_l0b_concat
    - disdrodb_run_l0b = disdrodb.l0.scripts.disdrodb_run_l0b:disdrodb_run_l0b
    - disdrodb_run_l0 = disdrodb.l0.scripts.disdrodb_run_l0:disdrodb_run_l0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - click
    - tqdm
    - pooch
    - donfig
    - requests
    - pyyaml
    - trollsift
    - h5py
    - netcdf4
    - pyarrow
    - pandas
    - dask-core
    - xarray
    - setuptools

test:
  imports:
    - disdrodb
  commands:
    - pip check
    - disdrodb_initialize_station --help
    - disdrodb_check_metadata_archive --help
    - disdrodb_download_archive --help
    - disdrodb_download_station --help
    - disdrodb_upload_archive --help
    - disdrodb_upload_station --help
    - disdrodb_run_l0a_station --help
    - disdrodb_run_l0a --help
    - disdrodb_run_l0b_station --help
    - disdrodb_run_l0_station --help
    - disdrodb_run_l0b_concat_station --help
    - disdrodb_run_l0b_concat --help
    - disdrodb_run_l0b --help
    - disdrodb_run_l0 --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ltelab/disdrodb
  summary: disdrodb provides tools to download, standardize, share and analyze global disdrometer data.
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ghiggi
